[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "speech2speech"
version = "0.1.0"
authors = [
  { name="rcdalj1", email="rcdalj1@gmail.com" },
]
description = "Source lang speech to machine translation to target lang speech"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/rcdalj/speech2speech"
"Bug Tracker" = "https://github.com/rcdalj/speech2speech/issues"