[project]
name = "TarkovCharacterTool"
version = "0.1.0"
description = "A tool used to create characters for Escape from Tarkov and allows users to rank their characters via leaderboards."
readme = "README.md"
requires-python = ">=3.11.1"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.11",
]
dependencies = [
  "tabulate"
]
[project.urls]
"Homepage" = "https://github.com/kakumei-consulting-mentees/Semester-Project"