[project]
name = "django_histories"
version = "1"
authors = [
  { name="QuantumaStelata", email="quantumastelata@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]