[project]
name = "forwarderd"
version = "11"
authors = [
  { name="Elchin Sarkarov", email="elchin751@gmail.com" },
]
description = "SSH Forward Daemon"
requires-python = ">=3.7"
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: POSIX",
  "Operating System :: Microsoft :: Windows",
]
dependencies = []
readme = "README.md"

[project.optional-dependencies]
daemon = ["paramiko", "sshtunnel"]

[tool.setuptools]
packages = ["forwarderd"]

[build-system]
requires = ["setuptools>=40.8.0"]
build-backend = "setuptools.build_meta"

[tool.pyright]
typeCheckingMode = "basic"
