[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.report]
show_missing = true

[project]
name = "ipfskvs"
version = "0.0.5"
description = "IPFS python client"
urls = {'Bug Tracker' = 'https://github.com/nanoswap/ipfskvs/issues'}
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: The Unlicense (Unlicense)'
]
authors = [{'name' = 'Nathaniel Schultz', 'email' = 'nate@nanoswap.finance'}]
requires-python = '>=3.11'
readme = 'README.md'
license = {'file' = 'LICENSE'}
dependencies = [
    "requests",
    "protobuf",
    "setuptools",
    "py-multicodec",
    "pandas",
]
