[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "study_id_generator"
version = "0.0.3"
authors = [
    { name="Sushant Obeja", email="sobeja@umich.edu" },
    { name="Adam Patterson", email="adpatter@umich.edu" },
]
description = "Study ID Generator."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    'requests >=2.28, < 3',
    'scikit-learn >= 1.1, < 2',
    'pandas >= 1.5, < 2',
    'numpy >= 1.23, < 2',
    'wxpython >= 4.1, < 5'
]

[project.urls]
"Homepage" = "https://git.umms.med.umich.edu/feldman-lab/study_id_generator"
"Bug Tracker" = "https://git.umms.med.umich.edu/feldman-lab/study_id_generator/-/issues"