[project]
name = "jeff_api"
version = "1.2.5"
authors = [
  { name="Mark CDA", email="aclo.create@gmail.com" },
]
description = "A Python library for intercommunicating with Jeff."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/markcda/jeff"
"Bug Tracker" = "https://github.com/markcda/jeff/issues"
