[tool.poetry]
name = "doji-core"
version = "0.1.4"
description = "A repository for Doji, a trade analytics suite written in Python."
authors = ["Sean O'Leary <seamicole@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "doji"}]

[tool.poetry.dependencies]
aiohttp = "^3.8.4"
pydantic = "^1.10.7"
python = "^3.10"
requests = "^2.28.2"
types-requests = "^2.28.11.17"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
mypy = "^1.1.1"
notebook = "^6.5.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
