[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "katalytic"
version = "0.1.1"
description = "This library abstracts away the details of common operations to catalyse progress without imposing the constraints frameworks usually come with"
license = {file = "LICENSE.txt"}
readme = "README.md"

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries",
    "Topic :: System :: Filesystems",
    "Topic :: System :: Systems Administration",
    "Topic :: Text Processing",
    "Topic :: Utilities",
]
keywords = [
    "automation",
    "high-level",
    "metaprogramming",
]
authors = [{name="Valentin Neagu", email="vali19th@protonmail.com"}]

requires-python = ">=3.6"
dependencies = [
	"katalytic-files>=0.3.2",
	"katalytic-pkg>=0.2.0",
]

[project.optional-dependencies]
all = [
	"katalytic-images>=0.1.0",
]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-randomly",
]

[project.urls]
homepage = "https://gitlab.com/katalytic/katalytic.git"
repository = "https://gitlab.com/katalytic/katalytic.git"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]

[tool.tox]
legacy_tox_ini = """
[tox]
env_list = py36, py37, py38, py39
isolated_build = True

[testenv]
extras = dev
deps = -e .

commands = pytest --cov-fail-under=100 --cov=katalytic --cov-report term-missing
"""

[tool.semantic_release]
version_variable = "pyproject.toml:version"
branch = "main"

[tool.flit.module]
name = "katalytic.katalytic"
