[tool.poetry]
name = "backend-sqlalchemy"
packages = [{include = "backend_sqlalchemy"}]
version = "0.1.5.dev.1681545553"
description = "Core for SQLAlchemy"
authors = ["Martin More <martinmore@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["sqlalchemy", "python", "backend"]

homepage = "https://example.com/"
repository = "https://github.com/martinmore-team/backend-sqlalchemy/"
documentation = "https://example.com/"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License",
]

[tool.poetry.urls]
"Discord" = "https://discord.com/invite/example123"
"Twitter" = "https://twitter.com/example123"
"Mastodon" = "https://farbun.social/@example123"
"Sponsor on GitHub" = "https://github.com/sponsors/example123"
"Sponsor on Open Collective" = "https://opencollective.com/example123"

[tool.poetry.dependencies]
python = "^3.10"
sqlalchemy = "^1.4"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.2"
pytest-cov = "^4.0.0"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^23.3.0"
pre-commit = "^3.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.autopub]
git-username = "martin-more"
git-email = "martinmore@gmail.com"
project-name = "backend-sqlalchemy"
append-github-contributor = true

src = ["backend_sqlalchemy"]
