[project]
name = "aiogram-ext"
version = "0.0.12"
description = ""
authors = []
dependencies = [
    "toml>=0.10.2",
    "aiogram>=2.25.1",
    "motor>=3.1.2",
    "mongoengine>=0.27.0",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-pep517>=1.0",
]
build-backend = "pdm.pep517.api"

[tool.pdm]
