[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sapiopylib"
version='2023.04.17.127'
authors = [
    { name="Yechen Qiao", email="yqiao@sapiosciences.com" },
]
description = "Official Sapio Informatics Platform Python API"
license = "MPL-2.0"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    'requests>=2.28.1', 'pandas>=1.3.0', 'flask>=2.2.0', 'buslane>=0.0.5'
]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Healthcare Industry",
    "Programming Language :: Python :: 3.7",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Software Development :: Libraries :: Python Modules",
    'Development Status :: 5 - Production/Stable',
]
homepage = "https://www.sapiosciences.com/"
keywords = ["lims", "eln", "rest", "sapio"]

[project.urls]
"Homepage" = "https://github.com/sapiosciences"
"Bug Tracker" = "https://github.com/sapiosciences/sapio-py-tutorials/issues"