[tool.poetry]
name = "statgis"
version = "1.0.6"
description = "Tools for improve work with geospatial data in Python"
authors = ["Sebástian Narváez-Salcedo <sanarvaezstatgis@gmail.com>", "Brayan Navarro-Londoño <brnavarrostatgis@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "<3.12,>=3.8"
earthengine-api = ">=0.1.335"
pandas = ">=1.3.5"
scipy = ">=1.7.3"
matplotlib = ">=3.2.2"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
pytest = ">=7.2.1"
ipython = ">=8.8.0"
pytest-cov = ">=4.0.0"
jupyterlab = ">=3.5.2"
ipykernel = ">=6.20.2"
myst-nb = {version = "^0.17.1", python = "^3.11"}
sphinx-autoapi = "^2.0.1"
sphinx-rtd-theme = "^1.1.1"
sphinxcontrib-napoleon = "^0.7"
sphinx-material = "^0.0.35"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
