[tool.poetry]
authors = ["Francisco Del Roio <francipvb@hotmail.com>"]
description = ""
name = "sqlalchemy-extras"
readme = "README.md"
version = "2.0.2"

[tool.poetry.dependencies]
sqlalchemy = "^2.0.9"
fastapi = { version = ">=0.60.0,<1.0.0", optional = true }
python = ">=3.10.0, <4"

[tool.poetry.extras]
fastapi = ["fastapi"]


[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
autoflake = "^2.0.2"
bandit = "^1.7.4"
black = "^23.1.0"
flake8 = "^6.0.0"
pytest = "^7.1.2"
pytest-cov = "^4.0.0"
pytest-sugar = "^0.9.4"
fastapi = ">=0.80.0, <1.0.0"
aiosqlite = "^0.18.0"
requests = "^2.28.1"
pytest-asyncio = "^0.21.0"
httpx = "^0.23.3"
ipykernel = "^6.22.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.isort]
profile = "black"
