[tool.black]
target-version = [
    "py311",
]
line-length = 120

[tool.pdm.build]
includes = [
    "fasm/",
    "trainerbase/",
]

[tool.pdm.dev-dependencies]
dev = [
    "black>=22.10.0",
    "pylint>=2.15.7",
]

[project]
name = "TrainerBase"
version = "2.10.0"
description = "Template/Framework to create game trainers"
authors = [
    { name = "v01d", email = "v01d@v01d.ru" },
    { name = "doomayka", email = "zd@doomayka.ru" },
]
dependencies = [
    "pymem>=1.10.0",
    "dearpygui>=1.8.0",
    "keyboard>=0.13.5",
    "pyttsx3>=2.90",
]
requires-python = ">=3.11"
readme = "README.md"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://gitlab.com/v01d-gamemods/trainer-base"

[build-system]
requires = [
    "pdm-pep517>=1.0",
]
build-backend = "pdm.pep517.api"
